//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceClient()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int ServiceClientID { get; set; }
        public int Service { get; set; }
        public string Amount { get; set; }
        public int Client { get; set; }
        public System.DateTime DateRegistr { get; set; }
        public System.DateTime DateExpires { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
